name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Recomendo 3.11 até que 3.13 esteja 100% estável no PyPI

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Executar testes com cobertura
        run: |
          pytest --cov=models --cov-report=xml

      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # pode remover se for repositório público
